name: Kernel - Build
on:
  workflow_dispatch:
    inputs:
      KERNEL_SOURCE_BRANCH:
        description: 'Kernel Branch'
        required: true
        default: 'lineage-23.2'

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Cloneing Kernel Source
      run: |
        git clone https://github.com/${{ github.server_url }}/${{ github.repository }}.git -b ${{ inputs.DEVICE_PATH }} kernel/

    - name: Installing dependencies
      run: |
        apt-get update && apt-get install --assume-yes --no-install-recommends autoconf automake bc bison build-essential ca-certificates cpio curl device-tree-compiler flex g++ gcc gcc-aarch64-linux-gnu gettext git-core gnupg gperf groff lib32ncurses5-dev lib32stdc++6 lib32z-dev libc6-dev libc6-dev-i386 libffi-dev libgl1-mesa-dev libncursesw5-dev libpopt-dev libssl-dev libtool libx11-dev libxml2-utils make ninja-build openjdk-8-jdk-headless openjdk-8-jre-headless openssh-client p7zip-full pkg-config python python3 python3-pip python3-venv rsync sudo unzip uuid-dev wget x11proto-core-dev xsltproc xz-utils zip zlib1g-dev

    - name: Building Kernel
      run: |
        cd kernel
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make fleur_defconfig
        make

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          arch/arm64/boot/Image.gz
        tag_name: ${{ github.run_id }}
        body: |
          ## Kernel Build - ${{ github.run_id }}